In [1]:
n=[1,2,3]

In [2]:
type(n)

list

In [3]:
n

[1, 2, 3]

In [4]:
m=np.array(n)

NameError: name 'np' is not defined

In [6]:
!pip install numpy

In [7]:
!pip install numpy

In [8]:
n

[1, 2, 3]

In [9]:
import numpy

In [10]:
m=np.array(n)

NameError: name 'np' is not defined

In [12]:
m=numpy.array(n)

m

In [13]:
m

array([1, 2, 3])

In [14]:
m.ndim

1

In [15]:
m.shape

(3,)

In [16]:
type(m)

numpy.ndarray

In [17]:
n=[1.0,True,"a",3]

In [18]:
n

[1.0, True, 'a', 3]

In [19]:
m=numpy.array(n)

In [20]:
m

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [21]:
type(m)

numpy.ndarray

In [22]:
m

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [23]:
n

[1.0, True, 'a', 3]

In [24]:
b=numpy.array([1,2,3], dtype="float64")

In [25]:
b

array([1., 2., 3.])

In [26]:
numpy.square(b)

array([1., 4., 9.])

In [27]:
b

array([1., 2., 3.])

In [28]:
c=numpy.array([4,5,6,7], dtype="int32")

In [29]:
c

array([4, 5, 6, 7])

In [30]:
b+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [31]:
c.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [32]:
c[-1]

7

In [33]:
c

array([4, 5, 6, 7])

In [34]:
b

array([1., 2., 3.])

In [35]:
d=numpy.array([8,9,10],dtype="int32")

In [36]:
c+d

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [37]:
c

array([4, 5, 6, 7])

In [38]:
d

array([ 8,  9, 10])

In [39]:
e=numpy.array([1,2,3],dtype="int32")

In [40]:
d+e

array([ 9, 11, 13])

In [41]:
d

array([ 8,  9, 10])

In [42]:
e

array([1, 2, 3])

In [43]:
d+e

array([ 9, 11, 13])

In [44]:
numpy.minimun(d,e)

AttributeError: module 'numpy' has no attribute 'minimun'

In [45]:
numpy.maximum(d,e)

array([ 8,  9, 10])

In [46]:
numpy.minimum(d,e)

array([1, 2, 3])

In [47]:
b.sort()

In [48]:
b

array([1., 2., 3.])

In [50]:
numpy.append(b,[9])

array([1., 2., 3., 9.])

In [51]:
b

array([1., 2., 3.])

In [52]:
rangos = range(3,28)

In [53]:
rangos

range(3, 28)

In [54]:
rangos = [3]

In [55]:
rangos

[3]

In [56]:
rangos.extend(range(4,28))

In [57]:
rangos

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27]

In [58]:
numpy.array(rangos)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [59]:
arregloNuevo = numpy.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [60]:
arregloNuevo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [61]:
arregloNuevo.sort()

In [70]:
arregloNuevo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [63]:
abc = arregloNuevo.sort()

In [65]:
abc

In [66]:
abc

In [67]:
type(abc)

NoneType

In [68]:
arregloNuevo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [69]:
arregloNuevo.sort()

In [73]:
a = np.arange(2,10,3)

In [72]:
import numpy as np

In [74]:
a

array([2, 5, 8])

In [75]:
b=np.arange(2,9)

In [76]:
b

array([2, 3, 4, 5, 6, 7, 8])

In [77]:
x=np.arange(-2,3)

In [78]:
y=np.arange(-2,3)

In [79]:
xy=np.array([x,y])

In [80]:
xy

array([[-2, -1,  0,  1,  2],
       [-2, -1,  0,  1,  2]])

In [81]:
b=np.reshape(np.array(range(1,26)),(5,5))

In [82]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
c=np.array(range(3,28))

In [84]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [85]:
e=np.eye(5,M=6,k=0,dtype="int32")

In [86]:
e

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [87]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])