In [7]:
rango = [3]

In [8]:
rango.extend(range(4,28))

In [9]:
import numpy as np

In [10]:
type(rango)

list

In [11]:
np.array(rango)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [24]:
arreglo = np.array(rango)

In [25]:
arreglo

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [26]:
arreglo2 = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [27]:
arreglo2.sort()

In [28]:
arreglo2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])